// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Use process.env directly so builds don't fail when DATABASE_URL is not set
// (e.g. during Vercel install where we may skip Prisma generation). If the
// variable is present, Prisma will use it as usual.
const databaseUrl = process.env.DATABASE_URL || "";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: databaseUrl,
  },
});
